import esbuild from "esbuild";
import sveltePlugin from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";
import fs from "fs";
import process from "process";

const isProd = process.argv.includes("--prod") || process.env.BUILD === "production";
const isWatch = process.argv.includes("--watch");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source visit the plugins github repository
*/
`;

const buildOptions = {
	entryPoints: ["src/main.ts"],
	bundle: true,
	outfile: "dist/main.js",
	format: "cjs",
	platform: "node",
	target: "esnext",
	sourcemap: "inline",
	sourcesContent: !isProd,
	external: ["obsidian"],
	banner: { js: banner },
	tsconfig: "tsconfig.json",
	minify: isProd,
	plugins: [
		sveltePlugin({
			preprocess: sveltePreprocess(),
			compilerOptions: {
				css: false,
			},
		}),
		{
			name: "post-build",
			setup(build) {
				build.onEnd(() => {
					if (!fs.existsSync("dist")) {
						fs.mkdirSync("dist");
					}
					if (fs.existsSync("dist/main.css")) {
						fs.renameSync("dist/main.css", "dist/styles.css");
					}
					if (fs.existsSync("manifest.json")) {
						fs.copyFileSync("manifest.json", "dist/manifest.json");
					}
				});
			},
		},
	],
};

const ctx = await esbuild.context(buildOptions);

if (isWatch) {
	await ctx.watch();
	console.log("esbuild: watching for changes...");
} else {
	await ctx.rebuild();
	await ctx.dispose();
}
